### ISSUE TITLE
Incorrect values displayed on Items to Farm/Breakdown

### ISSUE THREAD

**Issue by Eingkel** [GoodEffort/Arknights-Planner#25]
Hello, I stumbled upon this planner and I have been pleasantly surprised as i was looking for one, it has all the features I'm looking for !

Unfortunately, it seems that it has trouble calculating and displaying the required amount of items to farm, It applies to items that are craftable from lower tiers, uncraftable items such as grindstones, RMA or manganese ores are fine.

In my case, all craftable items have higher values than required, and most of them are frozen when I click on the crafting or -1/+1 buttons, or do massive jumps.
Examples : 
- Displaying 50 devices to farm, but if I add one in my inventory or by clicking on the +1 button once, it disappears.
- Displaying 350 orirock cubes, it gradually goes down to 300 like it should, then it jumps to 30 and the value freezes until it disappears as I keep increasing the amount of cubes available.
- 180 oriron clusters jumping to 53 with only three clicks.

I tried clearing the locale storage, and even on another browser, but the results were always the same.

Hope that I provided enough info to help !

**Comment by GoodEffort** [comment]
Is it moving them to the craft able items tab at that point? Would it be possible for you to click export at the top and paste that here? I won't be able to look at it for a few days, currently in England on a trip, but I can take a look when I'm back.

**Comment by Eingkel** [comment]
Yes, it moves them to the craft able items tab, and increasing the current inventory actually _increases_ the amount of items i have to craft on that tab, whereas the values on the items to farm tab _decreases_ a lot in one go.

There are a lot of registered operators and materials, but i've made it so that you can notice the big jumps in value in 3 incremental clicks with orirock cubes, devices, and oriron clusters.



{"s":["char_225_haak","char_4105_almond","char_218_cuttle","char_332_archet","char_4132_ascln","char_452_bstalk","char_137_brownb","char_369_bena","char_423_blemsh","char_328_cammou","char_159_peacok","char_130_doberm","char_4048_doroth","char_4123_ela","char_4036_forcer","char_241_panda","char_131_flameb","char_458_rfrost","char_1026_gvial2","char_109_fmout","char_297_hamoni","char_188_helage","char_1024_hbisc2","char_4027_heyak","char_491_humus","char_4124_iana","char_347_jaksel","char_214_kafka","char_4016_kazema","char_478_kirara","char_1021_kroos2","char_1011_lava2","char_322_lmlee","char_4133_logos","char_4130_luton","char_215_mantic","char_219_meteo","char_437_mizuki","char_455_nothin","char_148_nearl","char_1014_nearl2","char_250_phatom","char_204_platnm","char_144_red","char_1030_noirc2","char_451_robin","char_236_rope","char_202_demkni","char_254_vodfox","char_263_skadi","char_383_snsant","char_143_ghost","char_1023_ghost2","char_4015_spuria","char_358_lisa","char_1033_swire2","char_4145_ulpia","char_4107_vrdant","char_427_vigil","char_290_vigna","char_113_cqbw","char_400_weedy","char_1035_wisdel","char_115_headbr"],"i":{"2001":15100,"2002":14600,"2003":13200,"3211":39,"3212":18,"3213":1,"3221":61,"3222":38,"3223":17,"3231":37,"3232":28,"3233":4,"3241":34,"3242":13,"3243":5,"3251":65,"3252":41,"3253":4,"3261":33,"3262":38,"3271":26,"3272":28,"3273":4,"3281":35,"3282":55,"3283":4,"3301":2782,"3302":2441,"3303":228,"4001":33394600,"4006":7310,"30011":913,"30012":5732,"30013":20,"30014":2,"30021":667,"30022":1385,"30023":107,"30024":5,"30031":712,"30032":937,"30033":92,"30034":15,"30041":436,"30042":1210,"30043":410,"30044":4,"30051":473,"30052":1024,"30053":150,"30054":2,"30061":378,"30062":983,"30063":348,"30064":1,"30073":498,"30074":14,"30083":488,"30084":8,"30093":333,"30094":6,"30103":422,"30104":14,"30115":1,"30125":6,"30145":6,"30155":31,"31013":307,"31014":9,"31023":589,"31024":13,"31033":292,"31034":25,"31043":217,"31044":50,"31053":161,"31054":60,"31063":154,"31064":57,"31073":6,"31074":16,"31083":26,"31084":1,"32001":132,"mod_unlock_token":248,"mod_update_token_2":888,"mod_update_token_1":2945},"p":[{"operatorId":"char_225_haak","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":3},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":0},{"operatorId":"char_4105_almond","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":80,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":3,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":1},{"operatorId":"char_218_cuttle","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":2},{"operatorId":"char_332_archet","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":3},{"operatorId":"char_4132_ascln","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":0,"skill3":3},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":4},{"operatorId":"char_452_bstalk","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":0}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":5},{"operatorId":"char_137_brownb","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":6},{"operatorId":"char_369_bena","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":7},{"operatorId":"char_423_blemsh","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1},{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3},{"type":"X","level":3}]},"active":true,"sort":8},{"operatorId":"char_328_cammou","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":9},{"operatorId":"char_159_peacok","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":10},{"operatorId":"char_130_doberm","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":11},{"operatorId":"char_4048_doroth","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":12},{"operatorId":"char_4123_ela","plans":{"currentLevel":90,"currentElite":2,"currentSkillLevels":7,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":3},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":3},"targetModules":[{"type":"D","level":3}]},"active":true,"sort":13},{"operatorId":"char_4036_forcer","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":14},{"operatorId":"char_241_panda","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":15},{"operatorId":"char_131_flameb","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":16},{"operatorId":"char_458_rfrost","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":80,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":3,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":17},{"operatorId":"char_1026_gvial2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":18},{"operatorId":"char_109_fmout","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":19},{"operatorId":"char_297_hamoni","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":80,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":3,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":20},{"operatorId":"char_188_helage","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":3,"skill3":3},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":21},{"operatorId":"char_1024_hbisc2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":22},{"operatorId":"char_4027_heyak","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":3,"skill3":3},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":23},{"operatorId":"char_491_humus","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":24},{"operatorId":"char_4124_iana","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":25},{"operatorId":"char_347_jaksel","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":26},{"operatorId":"char_214_kafka","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":27},{"operatorId":"char_4016_kazema","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":28},{"operatorId":"char_478_kirara","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":29},{"operatorId":"char_1021_kroos2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":30},{"operatorId":"char_1011_lava2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":31},{"operatorId":"char_322_lmlee","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1},{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":32},{"operatorId":"char_4133_logos","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":3,"skill3":3},"targetModules":[{"type":"D","level":3}]},"active":true,"sort":33},{"operatorId":"char_4130_luton","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":70,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":3,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":34},{"operatorId":"char_215_mantic","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":35},{"operatorId":"char_219_meteo","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":36},{"operatorId":"char_437_mizuki","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":2}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":37},{"operatorId":"char_455_nothin","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":80,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":3,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":38},{"operatorId":"char_148_nearl","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":39},{"operatorId":"char_1014_nearl2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1},{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":40},{"operatorId":"char_250_phatom","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3},{"type":"A","level":0}]},"active":true,"sort":41},{"operatorId":"char_204_platnm","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":42},{"operatorId":"char_144_red","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":43},{"operatorId":"char_1030_noirc2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":44},{"operatorId":"char_451_robin","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":45},{"operatorId":"char_236_rope","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":46},{"operatorId":"char_202_demkni","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":2},{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":47},{"operatorId":"char_254_vodfox","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":48},{"operatorId":"char_263_skadi","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1},{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3},{"type":"X","level":3}]},"active":true,"sort":49},{"operatorId":"char_383_snsant","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":80,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":3,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":50},{"operatorId":"char_143_ghost","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":51},{"operatorId":"char_1023_ghost2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":52},{"operatorId":"char_4015_spuria","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":80,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":0,"skill2":3,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":53},{"operatorId":"char_358_lisa","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1},{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":54},{"operatorId":"char_1033_swire2","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":0}]},"active":true,"sort":55},{"operatorId":"char_4145_ulpia","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":3,"skill3":3},"targetModules":[{"type":"X","level":0}]},"active":true,"sort":56},{"operatorId":"char_4107_vrdant","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":57},{"operatorId":"char_427_vigil","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":58},{"operatorId":"char_290_vigna","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"Y","level":3}]},"active":true,"sort":59},{"operatorId":"char_113_cqbw","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1},{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":60},{"operatorId":"char_400_weedy","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1},{"type":"Y","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3},{"type":"Y","level":3}]},"active":true,"sort":61},{"operatorId":"char_1035_wisdel","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[],"targetLevel":90,"targetElite":2,"targetSkillLevels":7,"targetSkillMasteries":{"skill1":3,"skill2":3,"skill3":3},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":62},{"operatorId":"char_115_headbr","plans":{"currentLevel":1,"currentElite":0,"currentSkillLevels":1,"currentSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"currentModules":[{"type":"X","level":1}],"targetLevel":1,"targetElite":0,"targetSkillLevels":1,"targetSkillMasteries":{"skill1":0,"skill2":0,"skill3":0},"targetModules":[{"type":"X","level":3}]},"active":true,"sort":63}]}

**Comment by GoodEffort** [comment]
Ah, okay I see what's happening. It looks like you have 913 base Orirock and it's swapping it from farming to crafting when you hit that break point of not using up the "reserve amount" set in the "Reserved Items" modal. It should be piecing these out and not doing it all at once like it is now. I was working on fixing this bug a couple of weeks ago. The current workaround until I fix that (should be soon, this info helped) is to increase the "reserve" Orirock to a large number so it won't swap over which you can change in the "Crafting Recommendations (Beta)" tab and clicking "Edit Reserved Items"

**Comment by GoodEffort** [comment]
And you would repeat this for the other items too, currently it's checking all of those in bulk but it shouldn't.

**Comment by Eingkel** [comment]
Got it, thanks for the temporary fix and glad that the info helped !

**Comment by GoodEffort** [comment]
If you revert that temporary fix it should work as intended now, I think that was the last major bit of wonkiness with that feature. It is laid out a little differently in the UI now because pressing the +1/-1 buttons on the crafting section would make it look like nothing happened because you couldn't see the farming side.
