### ISSUE TITLE
Bug when applying multiple module levels

### ISSUE THREAD

**Issue by XaphIrongauntlet** [GoodEffort/Arknights-Planner#26]
When I have all 3 levels of a module in my planner, pressing Apply on level 1 removes it as expected, but it will then change level 2 and level 3 to a phantom level 1 and level 2.

![image](https://github.com/user-attachments/assets/01d321c8-2c41-4761-bd0c-0a7a8e50fa64)

![image](https://github.com/user-attachments/assets/34db2b3e-32e8-46fd-bea5-00c7ed7af266)

If I press Apply for this "new" level 1, it will deduct my materials but it won't upgrade the module in the planner from 1 > 2. It will stop me from pressing Apply if I don't have enough materials as expected, but otherwise it will allow me to keep pressing Apply until it drains all the materials from my planner.

Other upgrades seem to work properly, this appears to be just a module level issue.

**Comment by GoodEffort** [comment]
Ah I think I know what's causing that, won't be able to fix it for a few days as I'm away from my PC. But I think as a workaround clicking apply and then swapping tabs from items to plan then back to items should fix it
