### ISSUE TITLE
Enhancement request: "Missing Items"-section numbers reflect the excess lower tier materials that can be crafted to higher tier ones

### ISSUE THREAD

**Issue by Ohanaa99** [GoodEffort/Arknights-Planner#5]
First of all, I want to say that this is by far the best planner there is! It has almost all the convenience of GamePress planner before it broke. The latest EXP update was also an amazing addition. I am and will be using this planner at all times. Thank you so much for this!

Now to my point why I opened this issue (because I didn't also know where else to mention this and I wasn't sure if this issue was the "crafting recommendation" one on your README). I'd like to suggest a possible enhancement/optimization/fix to the planner. For me who plans operators way ahead into the future, I usually have and need lots of materials and skill summaries for lots of things. This results in needing for example 790 SS3 (Skill Summary - 3), 460 SS2 and 200 SS1. But if I have for example 390 SS3, 880 SS2 and 1370 SS1 in my inventory, it won't calculate the actual number of SS that I still need to farm without crafting or how many higher tier SS I can craft from lower tier ones without using needed amount of lower tier ones. 

I will mention another example this can be applied to. In my planner I need for example 200 Aketon (in itself + for higher tier crafts) and only 63 Polyketon. But in my inventory I have for example 176 Aketon and 417 Polyketon. The "Missing Items"-section still shows that I need 24 Aketon even though I have way too many Polyketon to craft those missing Aketons without needing to farm anything. 

These numbers would also be nice to reflect if I have excess lowest tier materials and I can craft highest tier materials from those (for example SS1 -> SS3 or Diketon -> Aketon). 

So my suggestion in short would be to somehow update the numbers under missing items to reflect the actual missing amount that needs to be farmed without crafting and add the number of how much I can and need to craft (for example Aketon or SS3) from lower tiers (Polyketon or SS2 or even lower tier ones). Possibly adding a "Needed to craft/Can be crafted"-section (like GamePress had before) where all the items that you need to craft are separated from the ones that need to be farmed from stages would be nice.

Thank you for considering this! (And sorry if you already had this planned for later.)

**Comment by GoodEffort** [comment]
Thanks for the compliments!

Yes, that is the plan eventually for the "crafting recommendations" part. It's a few different features I have in mind but that would be the main one where checking to see what mats you have available will be done, as well as the ability to reserve a subset (probably default 20 each) of "inefficient to farm" materials (T1/T2 excluding rocks). And also a BOM pop up feature for the item displays so you can see how and what to craft. 

It's probably 3rd on my current priorities right now because it's also annoying me that it doesn't do that yet, haha

**Comment by GoodEffort** [comment]
@Ohanaa99 I believe I have just now implemented this, it was a full rewrite of a lot of the missing items section so let me know if you run into any issues!

https://github.com/GoodEffort/Arknights-Planner/commit/90164bb8cef190f9a883ed177264168329a6f588

**Comment by GoodEffort** [comment]
https://github.com/GoodEffort/Arknights-Planner/commit/90164bb8cef190f9a883ed177264168329a6f588
