### ISSUE TITLE
[Bug] Exp card tracker broken

### ISSUE THREAD

**Issue by XaphIrongauntlet** [GoodEffort/Arknights-Planner#8]
It seems like remaining exp cards needed aren't being tracked again? I set something like 5 million exp worth of operators to build and it's not showing any exp cards in the Missing Items tab despite me only having 800 or so tier 3 exp cards and 50 tier 4 cards.

**Comment by GoodEffort** [comment]
Sorry about that, have a fix pushing now. Looks like there's some junk data getting in that function somewhere

**Comment by GoodEffort** [comment]
https://github.com/GoodEffort/Arknights-Planner/commit/a2dd0f2257bc5342812381ea7c25f4b8be052a21

**Comment by GoodEffort** [comment]
I broke it again

**Comment by GoodEffort** [comment]
I fixed it again
https://github.com/GoodEffort/Arknights-Planner/commit/b7db3f73e5ff1674bae96c06ba79ded81b4b753a
